title: MonitoredStop
modelClass: Piratmac\Idfm\Models\MonitoredStop
list: $/piratmac/idfm/models/monitoredstop/columns.yaml
recordUrl: 'piratmac/idfm/monitoredstop/update/:monitored_stop_id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 0
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
