title: Stops
modelClass: Piratmac\Idfm\Models\Stop
list: $/piratmac/idfm/models/stop/columns.yaml
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
